spring:
  application:
    name: customer-service

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      # in spring ${HOST} is the placeholder, localhost is the default value
      # in docker ${HOST} will be set as the container_name
      # ex. 'service-discovery'
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:8761/eureka
